language: python
python:
  - "2.7"

install:

    # command to install dependencies
    - python setup.py install
    - sudo pip install flake8

script:

    # command to run tests
    - flake8 .
    - nosetests python_webserver_installer/tests/
