language: python
python:
  - "2.7"

install:

    # command to install dependencies
    - export COSMO_BRANCH=$TRAVIS_BRANCH
    - python setup.py install

script:

    # command to run tests
    - python -m unittest python_webserver_installer.tests.test_python_webserver_installer