language: python
python:
  - "2.7"

install:

    # command to install dependencies
    - python setup.py install

    # command to install test dependencies
    - pip install -r test-requirements.txt

# command to run tests
script:
    - 'python -m unittest python_webserver_installer.tests.test_python_webserver_installer'